# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle & Publishing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetching branches 
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Execute permission for renaming script
      run: chmod +x renaming.sh
    - name: Running renaming script
      run: ./renaming.sh
      
      # Publishing to dev-builds branch
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        build_dir: build/libs
        target_branch: dev-builds
        keep_history: false
      env:
        GITHUB_PAT: ${{ secrets.pat }}
